In [1]:
import pandas as pd
import numpy as np

In [2]:
iris=pd.read_csv("iris.data")
iris.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [3]:
iris.columns.values

array(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype=object)

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
5.1            149 non-null float64
3.5            149 non-null float64
1.4            149 non-null float64
0.2            149 non-null float64
Iris-setosa    149 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [5]:
iris.isna().sum()

5.1            0
3.5            0
1.4            0
0.2            0
Iris-setosa    0
dtype: int64

In [3]:
d=iris.columns.values
df=pd.Series(d)

In [4]:
ar=['sepal length in cm','sepal width in cm','petal length in cm','petal width in cm','class']

In [5]:
iris.columns=ar
iris.head()

sepal length in cm  sepal width in cm  petal length in cm  \
0                 4.9                3.0                 1.4   
1                 4.7                3.2                 1.3   
2                 4.6                3.1                 1.5   
3                 5.0                3.6                 1.4   
4                 5.4                3.9                 1.7   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.4  Iris-setosa

In [9]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
sepal length in cm    149 non-null float64
sepal width in cm     149 non-null float64
petal length in cm    149 non-null float64
petal width in cm     149 non-null float64
class                 149 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [18]:
d

array(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype=object)

In [6]:
df=pd.DataFrame([d],columns=['sepal length in cm','sepal width in cm','petal length in cm','petal width in cm','class'])
df

sepal length in cm sepal width in cm petal length in cm petal width in cm  \
0                5.1               3.5                1.4               0.2   

         class  
0  Iris-setosa

In [7]:
iris=iris.append(df,ignore_index=True)

In [19]:
iris.shape

(150, 5)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
encode=LabelEncoder()

In [10]:
iris['class']=encode.fit_transform(iris['class'])

In [24]:
print(iris['class'])

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
120    2
121    2
122    2
123    2
124    2
125    2
126    2
127    2
128    2
129    2
130    2
131    2
132    2
133    2
134    2
135    2
136    2
137    2
138    2
139    2
140    2
141    2
142    2
143    2
144    2
145    2
146    2
147    2
148    2
149    0
Name: class, Length: 150, dtype: int32


In [27]:
iris1=pd.read_csv('iris.data')
iris1.columns=ar
iris1=iris1.append(df,ignore_index=True)
iris1.head()

sepal length in cm sepal width in cm petal length in cm petal width in cm  \
0                4.9                 3                1.4               0.2   
1                4.7               3.2                1.3               0.2   
2                4.6               3.1                1.5               0.2   
3                  5               3.6                1.4               0.2   
4                5.4               3.9                1.7               0.4   

         class  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [28]:
iris1.shape

(150, 5)

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [38]:
ct=ColumnTransformer([('encoder',OneHotEncoder(),[iris1['class']])],remainder='passthrough')
iris1['class']=np.array(ct.fit_transform(iris['class']), dtype=np.float)

IndexError: tuple index out of range

In [36]:
Onehotencoder=OneHotEncoder(categorical_features=[0])
iris['class']=Onehotencoder.fit_transform(iris['class']).toarray()

D:\anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


IndexError: tuple index out of range

 DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [11]:
x=iris.iloc[:,:-1].values
y=iris.iloc[:,-1].values

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [50]:
x_test

array([[6.4, 3.2, 5.3, 2.3],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 2.5, 5.8, 1.8],
       [4.4, 2.9, 1.4, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 2.3, 4.4, 1.3],
       [6.7, 3.0, 5.0, 1.7],
       [6.3, 2.5, 4.9, 1.5],
       [7.7, 3.0, 6.1, 2.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.4, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.5, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [4.4, 3.0, 1.3, 0.2],
       [5.7, 2.6, 3.5, 1.0],
       [6.1, 3.0, 4.6, 1.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [7.7, 2.8, 6.7, 2.0],
       [5.8, 2.7, 4.1, 1.0],
       [5.0, 3.0, 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [6.1, 3.0, 4.9, 1.8],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.0, 1.4, 0.3],
       [5.1, 2.5, 3.0, 1.1],
       [5.6, 2.7, 4.2, 1.3],
       [5.2, 3.5, 1.5, 0.2],
       [6.0, 3.0, 4.8, 1.8],
       [6.0, 3.4, 4.5, 1.6],
       [5.2, 3.4, 1.4, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [6.3, 2

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [15]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

D:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
y_pred=lr.predict(x_test)

In [58]:
y_pred==y_test

array([ True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False])

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[12,  1,  0],
       [ 0, 12,  4],
       [ 0,  0,  9]], dtype=int64)

In [61]:
print('Predicted Values on Test Data',encode.inverse_transform(y_pred))

Predicted Values on Test Data ['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica']


In [19]:
lr.score(y_test,y_pred)

ValueError: Expected 2D array, got 1D array instead:
array=[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [20]:
y_test.shape

(38,)

In [21]:
y_pred.shape

(38,)

In [24]:
lr.score(x_test,y_test)

0.868421052631579

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.868421052631579